enyo.depends(
	"cookie.js",
	"db8storage.js",
	"deviceProfile.js",
	"feeds.js",
	"filePicker.js",
	"help.js",
	"IPKGService.js",
	"packageModel.js",
	"packagesModel.js",
	"palmProfile.js",
	"savedPacketlist.js",
	"typeConditions.js",
	"globals.js"
);
