#!/bin/sh

PID="org.webosinternals.preware"
SID="org.webosinternals.ipkgservice"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Only remove the service if neither Preware or Preware Alpha will remain
if [ ! -f ${APPS}/usr/palm/applications/org.webosinternals.preware/appinfo.json -o \
     ! -f ${APPS}/usr/palm/applications/org.webosinternals.preware-alpha/appinfo.json ] ; then

  # Remove the ipkgservice executable
  rm -f /var/usr/sbin/${SID}

  # Remove the dbus service
  rm -f /usr/share/dbus-1/system-services/${SID}.service /var/palm/system-services/${SID}.service

  # Don't stop the service, because it is needed to remove the package
  # /sbin/stop ${SID} || true
  # /usr/bin/killall -9 ${PID} || true

  # Remove the upstart script
  rm -f /etc/event.d/${SID} /var/palm/event.d/${SID}

  # Remove all list database cache files
  rm -f $APPS/usr/lib/ipkg/lists/*
  rm -f $APPS/usr/lib/ipkg/cache/*

fi

exit 0
